apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::167325058662:user/Amitesh
      username: amitesh
      groups:
        - system:masters
