apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3BhdGllbnRhZG1pbkBwYXRpZW50LWluc2lnaHQtZGIuYzVtazJhOHVxZmgxLnVzLWVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3BhdGllbnRfcmVjb3Jkcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  aws-access-key-id: QUtJQVNONUtaWVpUTVE0TDdFUzc=
  aws-secret-access-key: QSt5MVRpNmI4WmZyMHhvdFNnZFF4VnpQTkE1akwrN1BtamJiRUo4Uw==