apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  database-url: <base64-encoded-db-url>
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  aws-access-key-id: <base64-encoded-access-key>
  aws-secret-access-key: <base64-encoded-secret-key> 