name: Data pipeline Unittests

on:
  push:
    branches:
      - main
    paths:
      - 'backend/data_pipeline/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run unittests
      run: |
        python -m unittest backend/data_pipeline/tests/test_data_download.py
        python -m unittest backend/data_pipeline/tests/test_data_preprocess.py

    - name: Notify on success
      if: success()
      run: echo "Unit tests passed successfully"

    - name: Notify on failure
      if: failure()
      run: echo "Unit tests failed"

  send_email:
    runs-on: ubuntu-latest
    needs: build  # Ensure `send_email` runs only after `build`
    if: failure()  # Run only if the `build` job fails

    steps:
    - name: Send email
      uses: dawidd6/action-send-mail@v4
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: GitHub Actions Workflow Failed
        to: pappuru.d@northeastern.edu, udayakumar.de@northeastern.edu, tripathi.am@northeastern.edu, gaddamsreeramulu.r@northeastern.edu, amin.sn@northeastern.edu
        from: mlopsgroup11@gmail.com
        body: |
          The workflow "${{ github.workflow }}" has failed.
            
          Repository: ${{ github.repository }}
          Workflow: ${{ github.workflow }}
          Run ID: ${{ github.run_id }}
          
          Check the logs here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}